import nodemailer from "nodemailer"

const emailConfig = {
  host: process.env.EMAIL_HOST,
  port: Number.parseInt(process.env.EMAIL_PORT || "587"),
  secure: process.env.EMAIL_SECURE === "true",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASSWORD,
  },
}

const transporter = nodemailer.createTransport(emailConfig)

export async function sendInsightNotification(to: string, insightTitle: string, insightSummary: string): Promise<void> {
  try {
    const mailOptions = {
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to,
      subject: `New AI Insight: ${insightTitle}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #333;">New Business Insight Generated</h2>
          <h3 style="color: #0066cc;">${insightTitle}</h3>
          <p style="color: #666; line-height: 1.6;">${insightSummary}</p>
          <p style="margin-top: 20px; color: #999; font-size: 12px;">
            This insight was generated by Biz AI based on your uploaded documents.
          </p>
        </div>
      `,
    }

    await transporter.sendMail(mailOptions)
    console.log("[v0] Insight notification sent to:", to)
  } catch (error) {
    console.error("[v0] Error sending insight notification:", error)
  }
}

export async function sendForecastNotification(to: string, forecastSummary: string): Promise<void> {
  try {
    const mailOptions = {
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to,
      subject: "Demand Forecast Update - Biz AI",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #333;">Demand Forecast Ready</h2>
          <p style="color: #666; line-height: 1.6;">${forecastSummary}</p>
          <p style="margin-top: 20px;">
            <a href="${process.env.EMAIL_FROM}" style="color: #0066cc; text-decoration: none;">
              View Full Forecast
            </a>
          </p>
          <p style="margin-top: 20px; color: #999; font-size: 12px;">
            View detailed forecasts in your Biz AI dashboard.
          </p>
        </div>
      `,
    }

    await transporter.sendMail(mailOptions)
    console.log("[v0] Forecast notification sent to:", to)
  } catch (error) {
    console.error("[v0] Error sending forecast notification:", error)
  }
}
